### ISSUE TITLE
Add digger:// support

### ISSUE THREAD

**Issue by ghost** [CyberShadow/Digger#1]
I thought it would be cool if we could add a link on each pull request page in the form of `digger://pull##`  (automatically, just like the autotester links). This would allow anyone who has digger installed to simply double-click the link which would invoke digger and build the compiler/libs/etc together with the specific pull request.

This would make it super-easy for anyone to try any specific pull request.

That would mean registering the protocol with digger on the target OS.

**Comment by CyberShadow** [comment]
Today, you can run:

```console
$ dub run -- digger build master+dmd#12345
```
or even
```console
$ dub run -- digger run master+dmd#12345 -- dmd -run test.d
```
(to compile `test.d` with DMD master plus a pull request).

I think that's more explicit / flexible / universal / cross-platform than a semi-opaque link, and does not require prior setup.

I've also ended up removing the web interface in v3, as I don't think anyone was really using it.
