### ISSUE TITLE
compilation error using dmd git head

### ISSUE THREAD

**Issue by evenex** [CyberShadow/Digger#11]
after checking out latest sources for Digger and dmd, I run:

rdmd --build-only digger

and get this:

ae/sys/file.d(277): Error: function ae.sys.file.atomic!(copy, "target/to/name/dst").atomic (const(char)[] _param_0, const(char)[] _param_1, Flag _param_2) is not callable using argument types (string, string)
ae/sys/git.d(304): Error: cannot cast expression rem[cast(ulong)(zi + 1L)..ei] of type immutable(ubyte)[] to ubyte[20]

**Comment by CyberShadow** [comment]
Fixed in latest ae update.
