### ISSUE TITLE
Error on Windows 8.1 64 bit

### ISSUE THREAD

**Issue by drtzack** [CyberShadow/Digger#18]
Everything is Ok

Folders: 264
Files: 3495
Size:       269313229
Compressed: 23420519
digger: Done installing GitInstaller.
digger: Adding C:\Users\Zekeriya\Desktop\digger\dl\gitinstaller\cmd to PATH.
digger: Updating repo...
Fetching origin
digger: Starting at meta repository commit 52f0eff168bd1e5dbf44bef69116ed9c107cf
43d
digger: Building components dmd, druntime, phobos-includes, phobos, rdmd
digger: needInstalled: dmd-c718790165c3124c61e510d8352b9cb9d8ae0198-f2fbc38e927c
ce53b6f819186b1ad93b
digger: Cache miss.
digger: needBuild: dmd-c718790165c3124c61e510d8352b9cb9d8ae0198-f2fbc38e927cce53
b6f819186b1ad93b
digger: Cleaning repository dmd...
digger: Not caching build failure due to temporary/environment error.
Fatal error: Command ["git", "--work-tree=C:\\Users\\Zekeriya\\Desktop\\digger\\
repo\\dmd", "--git-dir=c:\\Users\\Zekeriya\\Desktop\\digger\\repo\\.git\\modules
\\dmd", "rev-parse", "HEAD"] failed with status 128

**Comment by CyberShadow** [comment]
Is this with the latest beta or stable?

**Comment by drtzack** [comment]
Digger v2.2 beta 1

**Comment by drtzack** [comment]
Digger v2.1 (2015-05-03) works fine.

**Comment by CyberShadow** [comment]
I can't reproduce this. The error message indicates that the git is failing.

Can you consistently reproduce the error?

What happens when you run `git rev-parse HEAD` inside `C:\Users\Zekeriya\Desktop\digger\
repo\dmd`?

**Comment by drtzack** [comment]
I've just deleted all files and reinstalled now it works fine but 

digger build "v2.067.1+CyberShadow/druntime/diamond"

digger: Cleaning repository druntime...
HEAD is now at eeb01a6 Merge pull request #1227 from schveiguy/fixgcquery
digger: Merging 06ec477076c62d1f3b991cbcf182e0c5975be5da into eeb01a68b992af0e87
cbcf884a5aaf7a2035d2d6.
Auto-merging win64.mak
CONFLICT (content): Merge conflict in win64.mak
Auto-merging win32.mak
CONFLICT (content): Merge conflict in win32.mak
Auto-merging src/gc/gc.d
CONFLICT (content): Merge conflict in src/gc/gc.d
Auto-merging src/core/thread.d
Auto-merging posix.mak
CONFLICT (content): Merge conflict in posix.mak
Auto-merging mak/SRCS
Auto-merging mak/MANIFEST
Auto-merging mak/COPY
Automatic merge failed; fix conflicts and then commit the result.
digger: Aborting merge...
Fatal error: Command ["git", "--work-tree=c:\\Users\\Zekeriya\\Desktop\\digger\\
beta\\repo\\druntime", "--git-dir=c:\\Users\\Zekeriya\\Desktop\\digger\\beta\\re
po\\.git\\modules\\druntime", "merge", "--no-ff", "-m", "ae.sys.d merge", "06ec4
77076c62d1f3b991cbcf182e0c5975be5da"] failed with status 1

**Comment by CyberShadow** [comment]
The diamond branch isn't updated with 2.067 yet. The analyzer isn't ported to D2 yet as well.

**Comment by drtzack** [comment]
I see. I was trying to make an interpreter and when I saw your GC implementation, I thought I can use it and understand what you did.

Do you planning to update it?

**Comment by drtzack** [comment]
Also, Can I provide local dir instead of Username/dmd/awesome-feature

**Comment by CyberShadow** [comment]
> Do you planning to update it?

Yes, eventually.

> Also, Can I provide local dir instead of Username/dmd/awesome-feature

Not at the moment. You can push your fork to GitHub and then do that, though, or update the files in-place and use `digger rebuild`.
