### ISSUE TITLE
Build fails on Win32 for basic socket program

### ISSUE THREAD

**Issue by JakobOvrum** [CyberShadow/Digger#2]
```d
import std.socket;

void main() {}
```
Fails with:
```
OPTLINK (R) for Win32  Release 8.00.15
Copyright (C) Digital Mars 1989-2013  All rights reserved.
http://www.digitalmars.com/ctg/optlink.html
ws2_32.lib
 Warning 2: File Not Found ws2_32.lib
D:\Programming\d\Digger\builds\dev\result\bin\..\lib\phobos.lib(socket)
 Error 42: Symbol Undefined _WSAIoctl@36
--- errorlevel 1
```
Copying `ws2_32.lib` from a DMD archive release to the `<build>\dm\lib` directory fixes it.

P.S.
sc.ini has `WindowsSdkDir=\Program Files (x86)\Microsoft SDKs\Windows\v7.0A` - is the drive letter and colon supposed to be omitted like that? Same thing for the VCINSTALLDIR variable (although it also points to a non-existant directory).

**Comment by CyberShadow** [comment]
You can now use `digger install` to combine a full DMD install (with `ws2_32.lib` and others) with the latest DMD+Druntime+Phobos+Tools from git.

**Comment by CyberShadow** [comment]
You can now also build with `--with=extras` to get `ws2_32.lib` on Win32, among other things.
