### ISSUE TITLE
allow: digger build "master + github.com/D-Programming-Language/dmd/pull/4823"

### ISSUE THREAD

**Issue by timotheecour** [CyberShadow/Digger#22]
Would be nice to add this syntax to the list of supported digger build rules:

digger build "master + github.com/D-Programming-Language/dmd/pull/4823"

Makes copy paste from a pull request very simple.
(in addition to 
digger build "master + timotheecour/dmd/exclude_cwd_from_path"
)

https://github.com/CyberShadow/Digger/issues/1 is related but different; i'm just talking about command line here

**Comment by CyberShadow** [comment]
You know you can do `digger build master+dmd#4823` ?

**Comment by timotheecour** [comment]
overlooked, it thanks

perhaps modifying docs as follows would make it more discoverable:

# build with added pull request  github.com/D-Programming-Language/dmd/pull/123
$ digger build "master + dmd#123"

or perhaps it's already clear...
