### ISSUE TITLE
use 'make -j8' (or detect nb cores) by default; + how to configure?

### ISSUE THREAD

**Issue by timotheecour** [CyberShadow/Digger#23]
I'm seeing in logs this:
digger: Running: 'make' '-f' 'posix.mak' 'MODEL=64'
which explains why it's slow.
How would we configure to use make -j8 for example ? couldn't see it in README

**Comment by timotheecour** [comment]
I saw --make-args in changelog but doesn't seem to work:
./digger --make-args='j8' bisect /tmp/d04//bisect.ini.sample
doesn't work

Is there anything better than hacking into Digger/ae/sys/d/manager.d and changing
s/string[] makeArgs;/string[] makeArgs=["-j8"];/ ?

**Comment by timotheecour** [comment]
(that was well worth it btw, so should be a default: went from 1382 to 247 seconds)

**Comment by CyberShadow** [comment]
> ./digger --make-args='j8' bisect /tmp/d04//bisect.ini.sample

That's missing a leading `-` in front of `j8`

**Comment by timotheecour** [comment]
I had tried both:

std/getopt.d(611): Unrecognized option --make-args=-j8


So this option doesn't seem to work and also is not very discoverable:
digger --help doesn't show it and it's not in the README

**Comment by CyberShadow** [comment]
It is a parameter to `digger build`. You can see it by running `digger build --help`. This is documented when running `digger` or `digger --help`:

```
For help on a specific action, run: digger ACTION --help
```

You need to specify `--make-args` after the action (after `build`). This is in line with how other programs with subcommands work, such as git or svn.

**Comment by timotheecour** [comment]
but what about bisect?
digger bisect --make-args='-j8' /tmp/d04//bisect.ini.sample
Fatal error: Unrecognized option --make-args=-j8

**Comment by CyberShadow** [comment]
Oh right. That's configurable through `components.common.makeArgs` in the ini file but that's currently undocumented.

**Comment by CyberShadow** [comment]
Not sure if that'll actually work right now.

**Comment by CyberShadow** [comment]
87b9969c87784455712e046852ddb9a988147318
