### ISSUE TITLE
Digger should download smaller platform specific zip releases

### ISSUE THREAD

**Issue by MartinNowak** [CyberShadow/Digger#25]
I just noticed, that digger sometimes downloads the release builds, which is great to catch release build specific bugs.
It would save bandwidth and time to download the platform specific zip files instead of the combined one. The platform zips are used more often nowadays (e.g. by Travis-CI) so it's more critical that they work than the combined zip.

**Comment by CyberShadow** [comment]
Digger downloads these out of necessity, not testing (it needs a host DMD to build D parts of DMD with). If these are somehow incorrect, the build failures will be cached. The version numbers that are downloaded will also only change rarely, i.e. when the D DMD source code will start taking advantage of newer fixes/features not provided by the version Digger downloads at that moment.

I don't disagree with the goal of saving bandwidth though.

**Comment by CyberShadow** [comment]
Fixed in linked PR.
