### ISSUE TITLE
components.enable.phobos,druntime

### ISSUE THREAD

**Issue by timotheecour** [CyberShadow/Digger#28]
could we also have phobos and druntime as optional components to bisect dmd related bugs that have nothing to do with phobos and druntime?

**Comment by CyberShadow** [comment]
They already are (`phobos`, `phobos-includes`, `druntime`).

DMD includes `object.d` whether you want it or not. Sometimes you can get away with creating an empty `object.d` in the same directory.

It will also add `phobos.lib` or equivalent to the linker search path, so building Phobos is necessary if you want to link.
