### ISSUE TITLE
Fatal error: Bad commit is newer than good commit (and reverse search is enabled)

### ISSUE THREAD

**Issue by MartinNowak** [CyberShadow/Digger#31]
digger: Resolved GOOD revision `v2.070.0-b1` to 606072fbff4d36c9695137da9e3c0f48a6bf53b3.
digger: Resolved BAD revision `master @ 2015-12-01` to d05b21a27602e2aa0dfd5f3842a8215952d9d93e.

But the have those author and commit dates.
606072fb 2016-01-03 18:34:26
d05b21a2 2015-12-01 22:54:43

The log diff also looks a bit suspicious.
git log --oneline d05b21a2..606072fb

**Comment by CyberShadow** [comment]
Ah, that would be because they are on different branches. That code predates multiple branch D repos. The "oldness" in this case is determined by the distance (in commits) from master (commit/author dates are not relevant), but that only works if the commits have no common ancestor.

**Comment by CyberShadow** [comment]
Can you try 5d47b53d545b164005849df4f2263298c1bdf498 ?

**Comment by CyberShadow** [comment]
I guess this is fixed now.
