### ISSUE TITLE
Undefined symbols for architecture x86_64: __Unwind_GetIPInfo

### ISSUE THREAD

**Issue by timotheecour** [CyberShadow/Digger#32]
just rebuilt digger from scratch

./digger build #ok
./digger build --with=website

c++ -c -Wno-deprecated -Wstrict-aliasing -Wno-logical-op-parentheses -Wno-dynamic-class-memaccess -Wno-switch -fno-exceptions -fno-rtti -D__pascal= -DMARS=1 -DTARGET_OSX=1 -DDM_TARGET_CPU_X86=1 -m64 -Iroot -MMD -MF newdelete.deps root/newdelete.c
ld: warning: object file Digger/build/lib/libphobos2.a(errno_c.o)) was built for newer OSX version (10.11) than being linked (10.4)
Undefined symbols for architecture x86_64:
  "__Unwind_GetIPInfo", referenced from:
      ___dmd_personality_v0 in libphobos2.a(dwarfeh_5c9_811.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

Fatal error: Command ["make", "-f", "posix.mak", "all", "kindle", "pdf", "verbatim", "LATEST=2.071.0"] failed with status 2

**Comment by CyberShadow** [comment]
Did this work before for you?

**Comment by CyberShadow** [comment]
Does it work if you build by hand?

**Comment by CyberShadow** [comment]
@timotheecour ?

**Comment by MartinNowak** [comment]
Fixed with 2.071.1, see [Issue 15911 – undefined __Unwind_GetIPInfo for x86_64](https://issues.dlang.org/show_bug.cgi?id=15911).

**Comment by CyberShadow** [comment]
Thanks!
