### ISSUE TITLE
can digger build tools [https://github.com/D-Programming-Language/tools] ?

### ISSUE THREAD

**Issue by timotheecour** [CyberShadow/Digger#33]
it seems to build rdmd which is in tools, but not the other ones.

**Comment by CyberShadow** [comment]
Yes, right now it only builds rdmd.

**Comment by CyberShadow** [comment]
https://github.com/CyberShadow/Digger/commit/e32c89fa474e7813da3b3e23163953118cb52f33

**Comment by timotheecour** [comment]
dub run digger -- build "master + tools#271"
doesn't seen to be applying https://github.com/dlang/tools/pull/271#issuecomment-358605521
