### ISSUE TITLE
Register on dub

### ISSUE THREAD

**Issue by wilzbach** [CyberShadow/Digger#38]
It would be nice if the following directly works:

```sh
dub fetch digger && dub run digger
```

Idk how dub handles submodules exactly, but if it does clone them too than simply registering should work?

**Comment by CyberShadow** [comment]
I think it doesn't work currently, but I don't remember the details.

**Comment by timotheecour** [comment]
docs says: `A dub definition is also included, but you still need to clone with --recursive.`

however `dub search digger` fails

**Comment by CyberShadow** [comment]
Just because a dub definition is included doesn't mean that the project is registered on code.dlang.org (which is what this issue is about in the first place).

**Comment by timotheecour** [comment]
>> I think it doesn't work currently, but I don't remember the details.
`dub build`
works

`dub`
crashes (cf https://github.com/CyberShadow/Digger/issues/39)

so all in all dub build works; is there anything blocking registering it on dub ?

**Comment by CyberShadow** [comment]
Yes, as per my first comment here.

IIRC, dub's support for source libraries where the package root is the repository root is incomplete.

**Comment by CyberShadow** [comment]
http://code.dlang.org/packages/digger

Fixed?
