### ISSUE TITLE
[minor] digger crashes when you view the usage instructions

### ISSUE THREAD

**Issue by Cauterite** [CyberShadow/Digger#39]
```
c:\digger> digger.exe
Digger v2.4 - a D source code buil...
...
std.getopt.GetOptException@ae\utils\funopt.d(293): No action specified
----------------
0x0047058E
...
```

So it does its job of printing the usage instructions, but also dumps an ugly stack trace at the end of the output. Not a major problem, but it is a little confusing initially (notice stack trace -> assume something's gone wrong).

**Comment by CyberShadow** [comment]
It only does that if you compile with `-debug`, so I think we're all good here.

**Comment by Cauterite** [comment]
Then we are blocked by https://github.com/CyberShadow/Digger/issues/37 ;P

**Comment by CyberShadow** [comment]
Closing as this one is not really actionable.

**Comment by timotheecour** [comment]
how about:
in ./ae/utils/main.d

debug return run(args);
=>
```
auto fun(){
try return run(args);
catch(...){...}
}
```

```
version(workaround_issue_37) return fun(args);
else debug return run(args);
else return fun(args);
```

and then in instructions in README: write:
rdmd --build-only -debug -version=workaround_issue_37 digger

**Comment by CyberShadow** [comment]
Not a fan of temporary workarounds for bugs in other projects, especially for cosmetic issues. It would be more effective to complain to get the underlying DMD regression fixed.
