### ISSUE TITLE
why not build by default in ~/.digger/ instead of $PWD/ ?

### ISSUE THREAD

**Issue by timotheecour** [CyberShadow/Digger#44]
this is the usual behavior of other tools (eg dub, which builds in ~/.dub/ etc)
or any other name...
otherwise it's easy to end up with many installations in different directories wherever they were run...

at least an option for that?

**Comment by CyberShadow** [comment]
Tools which are downloaded and unpacked (as opposed to installed) generally operate in the current directory. This workflow is common for Windows tools.

Note that you can set `workDir` in the configuration file to any path you want.

**Comment by timotheecour** [comment]
`digger build` still builds in `$PWD`

```
grep workDir ~/.config/digger.ini
workDir=~/.config/digger/
```

also tried to put it in dir where digger binary is, but doesn't work.

These should as per instructions in:
https://github.com/CyberShadow/Digger/blob/master/digger.ini.sample#L16

# Additionally, for compatibility with previous versions,
# the following locations are searched:
# - ~/.digger/digger.ini

$XDG_CONFIG_HOME/digger (default ~/.config)
(i don't have XDG_CONFIG_HOME set so i'd assume it'd use ~/.config)

**Comment by CyberShadow** [comment]
If that's true, it indicates a bug...

**Comment by CyberShadow** [comment]
I can't reproduce this.

I pushed a commit that adds printing the configuration file and work directory paths. See what results you get with it.

**Comment by timotheecour** [comment]
i can't rebuild after the commit you pushed, see https://github.com/CyberShadow/Digger/issues/45

Also, I confirmed on another OS (ubuntu) that the above problem is there:

```
grep workDir ~/.config/digger.ini
workDir=~/.config/digger/
```

is ignored.

am i supposed to explicitly pass in the path to ~/.config/digger.ini in  `digger build`?

**Comment by CyberShadow** [comment]
You mean to say that you initially tested on a different version than latest git? No wonder.

**Comment by timotheecour** [comment]
uname
Darwin

git rev-parse HEAD
64df671aa5ecd2a552d25a2503c1602b97f3504e
(should include "I pushed a commit that adds printing the configuration file ")

rdmd --build-only -debug digger

pwd
/Users/timothee/temp/d02

/Users/timothee/git_clone/D/Digger/digger
Configuration file: (not present)
Working directory: /Users/timothee/temp/d02

grep workDir ~/.config/digger.ini
workDir=~/.config/digger/

am i missing something?

**Comment by CyberShadow** [comment]
Yes, please run `digger` with no arguments like I asked above.

**Comment by timotheecour** [comment]
that's what i did, see above (/Users/timothee/git_clone/D/Digger/digger)

**Comment by CyberShadow** [comment]
No idea why it's not finding the configuration file for you.

You *are* running the digger version you've just built, right? From your "log" excerpt it looks like you're building one version, then running another.

Otherwise try adding some debug writeln's here, to make it print the full locations it checks: https://github.com/CyberShadow/Digger/blob/master/config.d#L65

**Comment by timotheecour** [comment]
there were 2 cases:

* case 1: i was using a symlink to digger binary, looks like digger.ini is ignored when it's in the directory where the symlink is (but it works when digger.ini is in directory where realpath(symlink) is).

* case 2: my bad, i misread instructions, should've been `~/.config/digger/digger.ini`, not `~/.config/digger.ini`, sorry for the noise.

**Comment by CyberShadow** [comment]
Oh, I see. I had missed that as well. Glad to know it's resolved.

**Comment by timotheecour** [comment]
maybe this would be just a bit clearer in digger.ini.sample:
```
$XDG_CONFIG_HOME/digger (default ~/.config)
to:
$XDG_CONFIG_HOME/digger (XDG_CONFIG_HOME defaults to ~/.config)
likewise with
$XDG_CONFIG_DIRS/digger (default /etc/xdg)
```

**Comment by timotheecour** [comment]
related to case 1: above: https://issues.dlang.org/show_bug.cgi?id=16595

**Comment by CyberShadow** [comment]
> maybe this would be just a bit clearer in digger.ini.sample:

e08d3fc11d26185dbeb59f13aa840b0e1dace3ac
