### ISSUE TITLE
upon `digger build XXX` failure, issue a message with a working bisect command?

### ISSUE THREAD

**Issue by timotheecour** [CyberShadow/Digger#47]
this is to lower the bar for people to do bisection, which could improve a bit speed at which regressions are addressed...

(in response to your comment on https://issues.dlang.org/show_bug.cgi?id=16596)

this is a common use case so maybe even have a command line to do that without requiring to create a bisect.init file, eg:

```
echo "bad=master\ngood=@ 1 month ago\nbisectBuild=true\nreverse=false\ncomponents.enable.rdmd=false" | digger bisect -
```

`-` is commonly used to refer to reading from stdin so the syntax shouldn't be too weird

**Comment by CyberShadow** [comment]
> this is a common use case

Not really.

**Comment by CyberShadow** [comment]
> maybe even have a command line to do that without requiring to create a bisect.init file

d4d6acc2c1245680c8e0d1351912e993306b73a2 adds specifying bisect options on the command line.

> issue a message with a working bisect command

Digger still doesn't know what a working revision would be.

> this is a common use case

This was probably the first time someone other than me used the "bisectBuild" option.
