### ISSUE TITLE
how to build phobos shared library using digger build?

### ISSUE THREAD

**Issue by timotheecour** [CyberShadow/Digger#48]
http://downloads.dlang.org/pre-releases/2.x/2.072.0/dmd.2.072.0-b1.linux.tar.xz distributes a libphobos2.so, but digger build only seems to generate a .a static library

**Comment by CyberShadow** [comment]
Not currently implemented.

What's your use case?

**Comment by CyberShadow** [comment]
https://github.com/CyberShadow/ae/commit/11e3873535e1a1912ce9ffbbb6fd4f2093cb5211

**Comment by timotheecour** [comment]
thanks! use case=building shared libraries
