### ISSUE TITLE
linking digger fails

### ISSUE THREAD

**Issue by John-Colvin** [CyberShadow/Digger#52]
Only happened when building with rdmd, worked fine with dub. This is on macOS.

tried with latest dmd and ldc releases, in both cases I get 
```
Undefined symbols for architecture x86_64:
  "__D2ae5utils4sini63__T14makeIniHandlerTAyaTS2ae3sys1d7manager8DManager3DMD6ConfigZ14makeIniHandlerFNaNbNfKS2ae3sys1d7manager8DManager3DMD6ConfigZS2ae5utils4sini30__T20IniTraversingHandlerTAyaZ20IniTraversingHandler", referenced from:
      __D2ae5utils4sini77__T14makeIniHandlerTAyaTS2ae3sys1d7manager8DManager6Config5Build10ComponentsZ14makeIniHandlerFKS2ae3sys1d7manager8DManager6Config5Build10ComponentsZ12__dgliteral3MFAyaZS2ae5utils4sini30__T20IniTraversingHandlerTAyaZ20IniTraversingHandler in digger.o
```

**Comment by CyberShadow** [comment]
https://github.com/CyberShadow/Digger/issues/41 ?????

**Comment by CyberShadow** [comment]
I understand that it's frustrating that this bug still exists, but please search for duplicates before reporting issues... especially when those duplicates are duplicates of other issues that you've reported yourself. Closing...

**Comment by John-Colvin** [comment]
Ugh, totally forgot I'd reported this before and obviously didn't check properly. Sorry for the noise.
