### ISSUE TITLE
Cannot build recent dmd version for Win32

### ISSUE THREAD

**Issue by rainers** [CyberShadow/Digger#58]
Trying to build any dmd version of the last 3 month errors out with:
```
std.file.FileException@c:\l\d\dmd2.074\dmd2\windows\bin\..\..\src\phobos\std\file.d(1614): c:\s\d\Digger\repo\dmd\generated\windows\release\32\dmd.exe: The system cannot find the path specified.
```
It seems Digger expects a sub folder "windows" since the migration of the output files, but it's not in the "generated" folder. Dmd is build to generated\32\dmd.exe

Edit: not even "release" in the output path.

**Comment by CyberShadow** [comment]
Grrr. https://github.com/dlang/dmd/pull/6916

**Comment by CyberShadow** [comment]
Fixed, thanks!
