### ISSUE TITLE
Error: 'of..\generated\\release\32\idgen' not found

### ISSUE THREAD

**Issue by andre2007** [CyberShadow/Digger#62]
digger build "v2.074.1 + dmd#6760"

On windows 10 I try to build dmd and pull request 6760 (static foreach).
I tried different dmd versions (2.075 & 2.074). 
There is always following error:

```
of..\generated\\release\32\idgen ddmd\idgen.d
Error: 'of..\generated\\release\32\idgen' not found

--- errorlevel 1
digger: Not caching build failure due to temporary/environment error.
Fatal error: Command ["make", "-f", "win32.mak", "MODEL=32", "HOST_DC=", "dmd"] failed with status 1
```

[log.txt](https://github.com/CyberShadow/Digger/files/1140324/log.txt)

**Comment by CyberShadow** [comment]
Could you please build Digger from git? The current binary releases are outdated and can't build the latest D versions.

**Comment by andre2007** [comment]
I did the steps as described:
$ git clone --recursive https://github.com/CyberShadow/Digger
$ cd Digger
$ rdmd --build-only digger

C:\D\tools\Digger>rdmd --build-only digger
ae\sys\file.d(82): Deprecation: function std.utf.toUTF8 is deprecated - To be removed November 2017. Please use std.utf.encode instead.
ae\sys\file.d(82): Deprecation: function std.utf.toUTF8 is deprecated - To be removed November 2017. Please use std.utf.encode instead.
win32\commctrl.d(5307): Deprecation: Using the result of a comma expression is deprecated
win32\commctrl.d(6029): Deprecation: Using the result of a comma expression is deprecated
win32\commctrl.d(6029): Deprecation: Using the result of a comma expression is deprecated
OPTLINK (R) for Win32  Release 8.00.17
Copyright (C) Digital Mars 1989-2013  All rights reserved.
http://www.digitalmars.com/ctg/optlink.html
mpr.lib
 Warning 2: File Not Found mpr.lib
rpcns4.lib
 Warning 2: File Not Found rpcns4.lib
imm32.lib
 Warning 2: File Not Found imm32.lib
lz32.lib
 Warning 2: File Not Found lz32.lib
C:\Users\user\AppData\Local\Temp\.rdmd\rdmd-digger.d-19CB62597C7212487C2AC7F7EF58B92D\objs\digger.exe.obj(digger.exe)
 Error 42: Symbol Undefined _D2ae5utils4sini63__T14makeIniHandlerTAyaTSÇâ®3sys1d7manager8DMÇåë3DMD6ConfigZÇÉ╝FNaNbNfKÇº┐ÇäºüïÅ30üâÅ20Çâ¤TraverÇâögüïòZÇûø
Error: linker exited with status 1

**Comment by andre2007** [comment]
Tried via dub

dub run digger -- build "v2.074.1 + dmd#6760"

C:\D\tools\Digger>dub run digger -- build "v2.074.1 + dmd#6760"
Building package digger in C:\D\tools\Digger\
Fetching ae 0.0.1982 (getting selected version)...
Performing "debug" build using dmd for x86.
digger 3.0.0-alpha-5+commit.21.gd57927f: building configuration "application"...
..\..\..\Users\user\AppData\Roaming\dub\packages\ae-0.0.1982\ae\sys\file.d(82): Deprecation: function std.utf.toUTF8 is deprecated - To be removed November 2017. Please use std.utf.encode instead.
..\..\..\Users\user\AppData\Roaming\dub\packages\ae-0.0.1982\ae\sys\file.d(82): Deprecation: function std.utf.toUTF8 is deprecated - To be removed November 2017. Please use std.utf.encode instead.
Linking...
OPTLINK (R) for Win32  Release 8.00.17
Copyright (C) Digital Mars 1989-2013  All rights reserved.
http://www.digitalmars.com/ctg/optlink.html
.dub\build\application-debug-windows-x86-dmd_75-35A7120F6841C7A4B269A8F68E0601EC\digger.obj(digger)
 Error 42: Symbol Undefined _D5win325winnt16TOKEN_PRIVILEGES10PrivilegesMFZPS5win325winnt19LUID_AND_ATTRIBUTES
.dub\build\application-debug-windows-x86-dmd_75-35A7120F6841C7A4B269A8F68E0601EC\digger.obj(digger)
 Error 42: Symbol Undefined _D5win325winnt22SE_INCREASE_QUOTA_NAMExAa
.dub\build\application-debug-windows-x86-dmd_75-35A7120F6841C7A4B269A8F68E0601EC\digger.obj(digger)
 Error 42: Symbol Undefined _D5win328tlhelp3214PROCESSENTRY326__initZ
.dub\build\application-debug-windows-x86-dmd_75-35A7120F6841C7A4B269A8F68E0601EC\digger.obj(digger)
 Error 42: Symbol Undefined _D5win328tlhelp3213THREADENTRY326__initZ
.dub\build\application-debug-windows-x86-dmd_75-35A7120F6841C7A4B269A8F68E0601EC\digger.obj(digger)
 Error 42: Symbol Undefined _D5win328tlhelp3213MODULEENTRY326__initZ
.dub\build\application-debug-windows-x86-dmd_75-35A7120F6841C7A4B269A8F68E0601EC\digger.obj(digger)
 Error 42: Symbol Undefined _D5win327winuser11WNDCLASSEXW6__initZ
Error: linker exited with status 6
dmd failed with exit code 6.

**Comment by CyberShadow** [comment]
> Error 42: Symbol Undefined _D2ae5utils4sini63__T14makeIniHandlerTAyaTSÇâ®3sys1d7manager8DMÇåë3DMD6ConfigZÇÉ╝FNaNbNfKÇº┐ÇäºüïÅ30üâÅ20Çâ¤TraverÇâögüïòZÇûø

That would be #37.

> Error 42: Symbol Undefined _D5win325winnt16TOKEN_PRIVILEGES10PrivilegesMFZPS5win325winnt19LUID_AND_ATTRIBUTES

Hmm, that's a new one.

In any case, to build Digger from source, you can use the `-debug` switch with rdmd as described in the README to work around the DMD linking bug.

**Comment by CyberShadow** [comment]
> C:\D\tools\Digger>dub run digger -- build "v2.074.1 + dmd#6760"

I can't reproduce that link error with 2.074.1. What compiler are you using?

**Comment by CyberShadow** [comment]
> I can't reproduce that link error with 2.074.1. What compiler are you using?

I have a hunch that it's 2.075.0-b2, which was affected by https://issues.dlang.org/show_bug.cgi?id=17614.

**Comment by andre2007** [comment]
Yes I was using -b2. I updated now to -b4
and tried again using 

dub run digger -- build "v2.074.1 + dmd#6760"

...
Digital Mars Librarian Version 8.02n
Copyright (C) Digital Mars 2000-2007 All Rights Reserved
http://www.digitalmars.com/ctg/lib.html
Digital Mars Librarian complete.

C:\D\tools\Digger\work\dl\dmd-2.067.1\dmd2/windows/bin\dmd.exe -of..\generated\\release\32\idgen ddmd\idgen.d

..\generated\\release\32/idgen

if not exist "..\generated\\release\32" mkdir ..\generated\\release\32
copy ..\VERSION ..\generated\\release\32\VERSION
        1 Datei(en) kopiert.
if not exist "..\generated\\release\32" mkdir ..\generated\\release\32
C:\D\tools\Digger\work\dl\dmd-2.067.1\dmd2/windows/bin\dmd.exe -of..\generated\\release\32\lexer.lib -vtls -lib -J..\generated\\release\32 -O -release -inline -m32  -wi -version=MARS ddmd/console.d ddmd/entity.d ddmd/errors.d ddmd/globals.d ddmd/id.d ddmd/identifier.d  ddmd/lexer.d ddmd/tokens.d ddmd/utf.d ddmd\root/aav.d ddmd\root/array.d ddmd\root/ctfloat.d ddmd\root/file.d  ddmd\root/filename.d ddmd\root/man.d ddmd\root/outbuffer.d ddmd\root/port.d  ddmd\root/response.d ddmd\root/rmem.d ddmd\root/rootobject.d  ddmd\root/speller.d ddmd\root/stringtable.d ddmd\root/hash.d

if not exist "..\generated\\release\32" mkdir ..\generated\\release\32
copy ..\VERSION ..\generated\\release\32\VERSION
        1 Datei(en) kopiert.
C:\D\tools\Digger\work\dl\dmd-2.067.1\dmd2/windows/bin\dmd.exe  -of..\generated\\release\32\dmd.exe -vtls -J..\generated\\release\32 -J../res -L/STACK:8388608 -O -release -inline -m32  -wi -version=MARS -L/delexe/la ddmd/access.d ddmd/aggregate.d ddmd/aliasthis.d ddmd/apply.d ddmd/argtypes.d ddmd/arrayop.d        ddmd/arraytypes.d ddmd/astcodegen.d ddmd/attrib.d ddmd/builtin.d ddmd/canthrow.d ddmd/clone.d ddmd/complex.d              ddmd/cond.d ddmd/constfold.d ddmd/cppmangle.d ddmd/ctfeexpr.d ddmd/dcast.d ddmd/dclass.d                ddmd/declaration.d ddmd/delegatize.d ddmd/denum.d ddmd/dimport.d ddmd/dinifile.d ddmd/dinterpret.d        ddmd/dmacro.d ddmd/dmangle.d ddmd/dmodule.d ddmd/doc.d ddmd/dscope.d ddmd/dstruct.d ddmd/dsymbol.d              ddmd/dtemplate.d ddmd/dversion.d ddmd/escape.d                  ddmd/expression.d ddmd/func.d ddmd/hdrgen.d ddmd/imphint.d        ddmd/impcnvtab.d ddmd/init.d ddmd/inline.d ddmd/inlinecost.d ddmd/intrange.d ddmd/json.d ddmd/lib.d ddmd/link.d         ddmd/mars.d ddmd/mtype.d ddmd/nogc.d ddmd/nspace.d ddmd/objc.d ddmd/opover.d ddmd/optimize.d ddmd/parse.d         ddmd/sapply.d ddmd/sideeffect.d ddmd/statement.d ddmd/staticassert.d ddmd/target.d      ddmd/safe.d ddmd/blockexit.d ddmd/asttypename.d ddmd/printast.d  ddmd/traits.d ddmd/utils.d ddmd/visitor.d ddmd/libomf.d ddmd/scanomf.d ddmd/typinf.d  ddmd/libmscoff.d ddmd/scanmscoff.d ddmd/statement_rewrite_walker.d ddmd/statementsem.d ddmd/staticcond.d ddmd/irstate.d ddmd/toctype.d ddmd/glue.d ddmd/gluelayer.d ddmd/todt.d ddmd/tocsym.d ddmd/toir.d ddmd/dmsc.d  ddmd/tocvdebug.d ddmd/s2ir.d ddmd/toobj.d ddmd/e2ir.d ddmd/objc_glue_stubs.d ddmd/eh.d ddmd/iasm.d ddmd\backend/bcomplex.d ddmd\backend/cc.d ddmd\backend/cdef.d ddmd\backend/cgcv.d ddmd\backend/code.d ddmd\backend/cv4.d ddmd\backend/dt.d ddmd\backend/el.d ddmd\backend/global.d  ddmd\backend/obj.d ddmd\backend/oper.d ddmd\backend/outbuf.d ddmd\backend/rtlsym.d ddmd\backend/code_x86.d ddmd\backend/iasm.d  ddmd\backend/ty.d ddmd\backend/type.d ddmd\backend/exh.d ddmd\backend/mach.d ddmd\backend/md5.d ddmd\backend/mscoff.d ddmd\backend/dwarf.d ddmd\backend/dwarf2.d ddmd\backend/xmm.d ddmd\tk/dlist.d ddmd\root/aav.d ddmd\root/array.d ddmd\root/ctfloat.d ddmd\root/file.d  ddmd\root/filename.d ddmd\root/man.d ddmd\root/outbuffer.d ddmd\root/port.d  ddmd\root/response.d ddmd\root/rmem.d ddmd\root/rootobject.d  ddmd\root/speller.d ddmd\root/stringtable.d ddmd\root/hash.d ..\generated\\release\32\newdelete.obj ..\generated\\release\32\backend.lib ..\generated\\release\32\lexer.lib
Error: Internal Compiler Error: unsupported type (Array!(Dsymbol)* _param_1, bool _param_2)

Assertion failure: '0' on line 947 in file 'cppmangle.c'

abnormal program termination

--- errorlevel 1

--- errorlevel 1
digger: Saving to cache.
digger: Clearing temporary cache

object.Exception@..\..\..\Users\user\AppData\Roaming\dub\packages\ae-0.0.1959\ae\sys\d\manager.d(781): Command ["make", "-f", "win32.mak", "MODEL=32", "HOST_DC=C:\\D\\tools\\Digger\\work\\dl\\dmd-2.067.1\\dmd2/windows/bin\\dmd.exe", "dmd"] failed with status 1
----------------
0x0041066F in pure @safe void std.exception.bailOut!(Exception).bailOut(immutable(char)[], uint, const(char[])) at C:\D\dmd2\windows\bin\..\..\src\phobos\std\exception.d(431)
0x0041069E in pure @safe bool std.exception.enforce!(Exception, bool).enforce(bool, lazy const(char)[], immutable(char)[], uint) at C:\D\dmd2\windows\bin\..\..\src\phobos\std\exception.d(389)
0x004F1F30 in void ae.sys.d.manager.DManager.Component.run(const(immutable(char)[][]), const(immutable(char)[][immutable(char)[]]), immutable(char)[])
0x004F33C9 in void ae.sys.d.manager.DManager.DMD.performBuild() at C:\D\tools\Digger\..\..\..\Users\user\AppData\Roaming\dub\packages\ae-0.0.1959\ae\sys\d\manager.d(1019)
0x004F06E7 in void ae.sys.d.manager.DManager.Component.needBuild() at C:\D\tools\Digger\..\..\..\Users\user\AppData\Roaming\dub\packages\ae-0.0.1959\ae\sys\d\manager.d(503)
0x004F0AA8 in void ae.sys.d.manager.DManager.Component.needInstalled() at C:\D\tools\Digger\..\..\..\Users\user\AppData\Roaming\dub\packages\ae-0.0.1959\ae\sys\d\manager.d(600)
0x004F87E0 in void ae.sys.d.manager.DManager.build(ae.sys.d.manager.DManager.SubmoduleState, bool) at C:\D\tools\Digger\..\..\..\Users\user\AppData\Roaming\dub\packages\ae-0.0.1959\ae\sys\d\manager.d(1895)
0x004B3DD5 in void custom.runBuild(immutable(char)[], ae.sys.d.manager.DManager.SubmoduleState) at C:\D\tools\Digger\..\..\..\Users\user\AppData\Roaming\dub\packages\digger-3.0.0-alpha-5\digger\custom.d(57)
0x004B546C in void custom.buildCustom(immutable(char)[]) at C:\D\tools\Digger\..\..\..\Users\user\AppData\Roaming\dub\packages\digger-3.0.0-alpha-5\digger\custom.d(271)
0x004B576C in D6digger6Digger5buildFS2ae5utils6funopt102__T10OptionImplVE2ae5utils6funopt10OptionTypei0TbVAyaC371CA8D2FA4B679DAE45954C7051303 at C:\D\tools\Digger\..\..\..\Users\user\AppData\Roaming\dub\packages\digger-3.0.0-alpha-5\digger\digger.d(69)
0x00534BB6 in D2ae5utils6funopt3056__T6funoptS2741_D6digger6Digger5buildFS2ae5utils6funopt102__T10OptionImplV2EBDA24A0F968D2CD68083F19205EAEB at C:\D\tools\Digger\..\..\..\Users\user\AppData\Roaming\dub\packages\ae-0.0.1959\ae\utils\funopt.d(304)
0x00533A79 in int ae.utils.funopt.__T14funoptDispatchTS6digger6DiggerVS2ae5utils6funopt12FunOptConfigS1nS33_D6digger6diggerFZ8usageFunFAyaZvZ.funoptDispatch(immutable(char)[][]).fun(immutable(char)[], immutable(char)[][]) at C:\D\tools\Digger\..\..\..\Users\user\AppData\Roaming\dub\packages\ae-0.0.1959\ae\utils\funopt.d(569)
0x00547314 in D2ae5utils6funopt390__T6funoptS165_D2ae5utils6funopt107__T14funoptDispatchTS6digger6DiggerVS2ae0F6B43049C1CA18E0CE62171B0D377D0 at C:\D\tools\Digger\..\..\..\Users\user\AppData\Roaming\dub\packages\ae-0.0.1959\ae\utils\funopt.d(304)
0x0053393C in int ae.utils.funopt.__T14funoptDispatchTS6digger6DiggerVS2ae5utils6funopt12FunOptConfigS1nS33_D6digger6diggerFZ8usageFunFAyaZvZ.funoptDispatch(immutable(char)[][]) at C:\D\tools\Digger\..\..\..\Users\user\AppData\Roaming\dub\packages\ae-0.0.1959\ae\utils\funopt.d(583)
0x004B5D86 in int digger.digger() at C:\D\tools\Digger\..\..\..\Users\user\AppData\Roaming\dub\packages\digger-3.0.0-alpha-5\digger\digger.d(249)
0x004B61AC in int digger.__mixin21.run(immutable(char)[][]) at C:\D\tools\Digger\..\..\..\Users\user\AppData\Roaming\dub\packages\ae-0.0.1959\ae\utils\main.d(40)
0x004B61BE in _Dmain at C:\D\tools\Digger\..\..\..\Users\user\AppData\Roaming\dub\packages\ae-0.0.1959\ae\utils\main.d(69)
0x005BEA73 in D2rt6dmain211_d_run_mainUiPPaPUAAaZiZ6runAllMFZ9__lambda1MFZv
0x005BEA37 in void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).runAll()
0x005BE938 in _d_run_main
0x004B6928 in main at C:\D\tools\Digger\..\..\..\Users\user\AppData\Roaming\dub\packages\digger-3.0.0-alpha-5\digger\bisect.d(7)
0x0061DF25 in mainCRTStartup
0x748A62C4 in BaseThreadInitThunk
0x77C20FD9 in RtlSubscribeWnfStateChangeNotification
0x77C20FA4 in RtlSubscribeWnfStateChangeNotification
Program exited with code 1

**Comment by CyberShadow** [comment]
> Assertion failure: '0' on line 947 in file 'cppmangle.c'

It looks like a bug in the pull request you're trying to build.

There isn't much Digger can do about this.
