### ISSUE TITLE
can digger be used with a local clone of dmd (or phobos or druntime or tools) ?

### ISSUE THREAD

**Issue by timotheecour** [CyberShadow/Digger#64]
eg:
```
dub run digger -- build "master +dmd#7757  tools:/path/to/tools"
```

**Comment by CyberShadow** [comment]
No, Digger cannot use an existing checkout from somewhere else. Digger needs to manage the git checkouts it creates, and it does things like storing metadata under `.git/`, and coordinating the repository's state with that of the meta-repository that D components are submodules of.
