### ISSUE TITLE
digger/work/result/bin should only contain executables, not ".o" object files

### ISSUE THREAD

**Issue by timotheecour** [CyberShadow/Digger#66]

**Comment by CyberShadow** [comment]
```
$ digger build
...

To start using it, run `digger install`, or add /home/vladimir/work/Digger/work/result/bin to your PATH.

$ ls ~/work/Digger/work/result/bin
dmd  dmd.conf  rdmd
```
Unable to reproduce.

**Comment by timotheecour** [comment]
interesting... i''m getting:

ls /Users/timothee/temp/digger/work/result/bin/
catdoc                  changed                 checkwhitespace         contributors            ddemangle               detab                   dget                    dmd                     dustmite                rdmd                    tolf
catdoc.o                changed.o               checkwhitespace.o       contributors.o          ddemangle.o             detab.o                 dget.o                  dmd.conf                dustmite.o              rdmd.o                  tolf.o

(i have components.enable.tools = true)

**Comment by timotheecour** [comment]
indeed, the object files only occur when we add `components.enable.tools = true`
(without this, rdmd.o isn't added; with it, rdmd.o is added along with other .o)

**Comment by CyberShadow** [comment]
Fixed, thanks.
