### ISSUE TITLE
../../../.dub/packages/ae-0.0.1959/ae/utils/zlib.d(43,9): Error: constructor calls not allowed in loops or after labels

### ISSUE THREAD

**Issue by timotheecour** [CyberShadow/Digger#72]
dub run digger -- build "master"
../../../.dub/packages/ae-0.0.1959/ae/utils/zlib.d(43,9): Error: constructor calls not allowed in loops or after labels

**Comment by CyberShadow** [comment]
Fix your Dub or Dub configuration. It's using a very old version of ae, this was fixed a long time ago.

**Comment by CyberShadow** [comment]
Hmm, maybe there is a problem with Dub?

A sure-proof way would be to delete ~/.dub, the Digger directory if you cloned it yourself, then try again.
