### ISSUE TITLE
Windows / build older version fails

### ISSUE THREAD

**Issue by Robert-M-Muench** [CyberShadow/Digger#80]
I don't understand why I get this `fatal: ambiguous argument 'origin/v2.088.1': unknown revision or path not in the working tree.` How am I supposed to specify a specific version?

And `object.Exception@ae\sys\d\repo.d(537): The worktree has changed since the last time this software updated it.`because last time I just build the head and didn't do anything in between.

```
D:\develop\d-language\Digger> .\digger build --model=64 v2.088.1
digger: Building spec: v2.088.1
digger: Updating repo...
Fetching origin
fatal: ambiguous argument 'origin/v2.088.1': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
digger: Starting at meta repository commit b7a303005afce50f317c768311b71bc21d47090d
digger: Building components dmd, druntime, phobos-includes, phobos, rdmd
digger: needInstalled: dmd-8a2067c4bd9c720098c8acb5429f189b12b32ab6-e9129fa50e7d77eb055e162ea4e496b4
digger: Clearing temporary cache
digger: Cache miss.
digger: needBuild: dmd-8a2067c4bd9c720098c8acb5429f189b12b32ab6-e9129fa50e7d77eb055e162ea4e496b4
digger: Not caching dmd build failure due to temporary/environment error.

object.Exception@ae\sys\d\repo.d(537): The worktree has changed since the last time this software updated it.
Specifically:
    File modified: test/compilable/test19954.d (modification time changed, before: 2019-Oct-10 20:32:58.0359794, after: 2019-Oct-10 20:32:58.0359795)

Aborting to avoid overwriting your changes.
To continue:
 1. Commit / stash / back up your changes, if you wish to keep them
 2. Delete D:\develop\d-language\Digger\work\repo\.git\modules\dmd\ae-sys-d-worktree.json
 3. Try this operation again.
----------------
```

**Comment by CyberShadow** [comment]
> I don't understand why I get this `fatal: ambiguous argument 'origin/v2.088.1': unknown revision or path not in the working tree.` How am I supposed to specify a specific version?

This is not an error displayed for your information, it is Digger trying things out to figure out what format the version specification you supplied is in. I agree that the error should be hidden from users to avoid confusion.

> And `object.Exception@ae\sys\d\repo.d(537): The worktree has changed since the last time this software updated it.`because last time I just build the head and didn't do anything in between.

This sometimes happens when a Digger operation is interrupted. If you have no data to save, just follow steps 2-3.

**Comment by CyberShadow** [comment]
> before: 2019-Oct-10 20:32:58.0359794, after: 2019-Oct-10 20:32:58.0359795

Hmm, the difference is just about 100 nanoseconds. Why would the OS report a timestamp with a 100-nanosecond difference between different `FindFirstFileW` calls?

**Comment by Robert-M-Muench** [comment]
I'm running Digger in a VM on OSX using a network share as the build directory. Maybe there is a short lag.

**Comment by CyberShadow** [comment]
> I'm running Digger in a VM on OSX using a network share as the build directory.

Please include information like this in the initial bug report.

The configuration you are using is unsupported. If you intend to continue using Digger with this configuration, please do not open new issues unless you can reproduce the problem on a local filesystem.

**Comment by Robert-M-Muench** [comment]
Sorry, I missed this VM information.

Now running digger on the local drive of the VM, which works for `.\digger.exe build --model=64 ` but gives an error when run as `.\digger.exe build --model=64 v2.088.1`:

```
Digital Mars Librarian Version 8.02n
Copyright (C) Digital Mars 2000-2007 All Rights Reserved
http://www.digitalmars.com/ctg/lib.html
Digital Mars Librarian complete.

C:\tmp\digger-win\work\dl\dmd-2.079.0\dmd2/windows/bin\dmd.exe -of..\generated\build.exe -debug build.d

..\generated\build.exe --called-from-make OS=windows BUILD=release MODEL=32 HOST_DMD= HOST_DC=C:\tmp\digger-win\work\dl\dmd-2.079.0\dmd2/windows/bin\dmd.exe ..\generated\windows\release\32\lexer.lib

std.process.ProcessException@std\process.d(752): Failed to spawn new process (Das System kann die angegebene Datei nicht finden.)
----------------
0x004387BC
0x0044121E
0x00454C4C
0x00444A80
0x0042C8F4
0x004039CD
0x0040258D
0x004354E7
0x00435469
0x00435304
0x00429577
0x777F6359 in BaseThreadInitThunk
0x77A67B74 in RtlGetAppContainerNamedObjectPath
0x77A67B44 in RtlGetAppContainerNamedObjectPath

--- errorlevel 1

--- errorlevel 1
digger: Saving to cache.
digger: Clearing temporary cache

object.Exception@ae\sys\d\manager.d(850): Command ["make", "-f", "win32.mak", "MODEL=32", "HOST_DC=C:\\tmp\\digger-win\\work\\dl\\dmd-2.079.0\\dmd2/windows/bin\\dmd.exe", "dmd"] failed with status 1
----------------
```
The german message means: The system can't find the specified file

Sidenote: How about adding a big statement to the readme that if digger is run using a VM it should work on the VM local drive. I think I was hit by this in the past too because it gives some strange behavior which isn't obviously giving a hint, that the VM setup is the problem.

**Comment by CyberShadow** [comment]
> but gives an error when run as `.\digger.exe build --model=64 v2.088.1`:

This was a bug in the new build system at the time:

https://github.com/CyberShadow/Digger/issues/78

I guess Digger needs to work around it to build that version range. I don't have access to a Windows system at the moment, though.

> Sidenote: How about adding a big statement to the readme that if digger is run using a VM it should work on the VM local drive. I think I was hit by this in the past too because it gives some strange behavior which isn't obviously giving a hint, that the VM setup is the problem.

Honestly, I don't think it's necessary because it's one of infinite weird configurations that software in general is just not going to reliably work on. I feel like it's self-implied that if you try to do anything non-trivial on a non-local filesystem, things just aren't going to work because they simply cannot provide the same guarantee as a local filesystem. If you file a bug against software that heavily relies on the filesystem to do its job and mention "oh and also I'm running this on a remote filesystem", you will get the same response with most projects.

**Comment by Robert-M-Muench** [comment]
I can confirm that building v2.087.1 works.

**Comment by GoaLitiuM** [comment]
``digger build "v2.088.1 + dmd#10490 + dmd#10491"`` should workaround the issue for now.

**Comment by CyberShadow** [comment]
> `digger build "v2.088.1 + dmd#10490 + dmd#10491"` should workaround the issue for now.

Unfortunately this will pull in all commits from those pull request's base branches, as Digger does a `git merge` and not `rebase` / `cherry-pick`. (Probably I should change that.)

**Comment by Robert-M-Muench** [comment]
If it's only version v2.088.1, which makes problems, why not just catch it and let the user know? IMO that would be perfectly OK. Most likely it's not worth to fiddle around with this particular case.

Or add a "live patch" feature to repair things for specific versions? That would be awesome, making Digger the one-stop-shop for building DMD.

BTW: Thanks a lot for making Digger, it's a valuable tool and makes working with DMD and long-term projects a lot simpler because if there is a breaking-change in the tool-chain, I can step back.

**Comment by CyberShadow** [comment]
> Or add a "live patch" feature to repair things for specific versions? That would be awesome, making Digger the one-stop-shop for building DMD.

Yes, Digger does do that, just not for that particular problem right now. See e.g. https://github.com/CyberShadow/ae/blob/9841561d97eb799c41e60adaf142030f59372c35/sys/d/manager.d#L1032-L1060.

**Comment by Robert-M-Muench** [comment]
Wow... very good. I didn't know that.
