### ISSUE TITLE
building with DUB is broken

### ISSUE THREAD

**Issue by NilsLankila** [CyberShadow/Digger#83]
> $ dub build --compiler=ldc2  
Performing "debug" build using ldc2 for x86_64.
digger 3.0.1: building configuration "application"...
../../../.dub/packages/ae-0.0.2609/ae/net/oauth/common.d(69,21): Deprecation: alias ae.utils.aa.HashCollection!(string, string, false, true).HashCollection.getAll is deprecated
Linking...
.dub/build/application-debug-linux.posix-x86_64-ldc_2091-9630FB35DA32FF332E4610FD690C651C/digger.o:wininet.d:_D6digger12__ModuleInfoZ : erreur : référence à « _D2ae3sys3net4curl12__ModuleInfoZ » non définie
collect2: erreur: ld a retourné le statut de sortie 1
Error: /usr/bin/cc failed with status: 1
ldc2 failed with exit code 1.

rdmd still works.

**Comment by CyberShadow** [comment]
I think this is fixed now (or, at least, no longer reproducible). Please leave a comment otherwise.
