### ISSUE TITLE
Increase `ae` dependency

### ISSUE THREAD

**Issue by JohanEngelen** [CyberShadow/Digger#95]
Is it needed to pin the ae dependency to a specific version `dependency "ae" version="==0.0.2845"` ?
Updating to latest ae would include the fix https://github.com/CyberShadow/ae/issues/54, such that digger can be built on Apple M1 with LDC.

**Comment by CyberShadow** [comment]
> Is it needed to pin the ae dependency to a specific version `dependency "ae" version="==0.0.2845"` ?

Dependency pinning is done to keep builds as reproducible as possible.

> Updating to latest ae would include the fix [CyberShadow/ae#54](https://github.com/CyberShadow/ae/issues/54), such that digger can be built on Apple M1 with LDC.

Was this the only problem that was preventing you from using Digger to achieve your goal? I wouldn't be surprised of more trouble related to AArch64.

**Comment by JohanEngelen** [comment]
This and removing the zlib link were the only two changes needed to build Digger with LDC 1.27.
Using Digger worked well when using DMD 2.099 as bootstrap compiler.
