### ISSUE TITLE
dmd master fails to build 

### ISSUE THREAD

**Issue by AndrejMitrovic** [CyberShadow/Digger#98]
On WSL1:

> object.Exception@/home/drey/.dub/packages/ae-0.0.3227/ae/sys/d/manager.d(898): Command ["make", "-f", "posix.mak", "DMD=/c/dev/digger-test/work/build/bin/dmd", "MODEL=64"] failed with status 2

Log file: https://gist.github.com/AndrejMitrovic/6bb7e3f0b86dc7c4cd6e35efdd9d0ca0

**Comment by CyberShadow** [comment]
Thanks! I tagged v3.0.9 which should fix this.

The problem occurs on systems where `/bin/sh` does not understand Bash-style `{...}` expansions; I accidentally introduced them in the now-archived Druntime repository.

**Comment by AndrejMitrovic** [comment]
>The problem occurs on systems where /bin/sh does not understand Bash-style {...} expansions

Oh I guess `zsh` is to blame.

> Thanks! I tagged v3.0.9 which should fix this.

Thanks a lot! I'll wait for it to propagate to https://code.dlang.org/packages/digger.

**Comment by AndrejMitrovic** [comment]
Thanks again, confirmed to work.
